import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Layout from "@/components/layout/Layout";
import ReactQueryProvider from "@/config/provider/ReactQueryProvider";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["500", "700", "600", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReactQueryProvider>
          <Layout>{children}</Layout>
        </ReactQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
